### ISSUE TITLE
Add comment to order

### ISSUE THREAD

**Issue by alexanderforret** [Steerlin/foodleader#1]
The possibility to add a comment to your order, like if you want to order a sandwich with brown bread instead of white

**Comment by Steerlin** [comment]
I think a comment should be an exception (like "I'm allergic to bread, so no bread please") and brown/white should be a mandatory choice / option if required ?

**Comment by Steerlin** [comment]
Also one comment per day or per ordered item ?

**Comment by alexanderforret** [comment]
I think this is an interesting site for ordering food. They do it like you say. That you can choose the normal stuff and that you can add a comment for your complete order for one day.
http://bakkersonline.be/patisseriediva
